# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_share', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='newFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('shared_key', models.TextField(blank=True, null=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_share.Folder')),
            ],
        ),
    ]
