# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 19:34
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_share', '0002_newfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordChangeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('time', models.DateField(default=datetime.date.today)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
