# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 13:29
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170311_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='myapp.Genre'),
        ),
    ]
